### ISSUE TITLE
 raise AttributeError(name) from None AttributeError: _2D

### ISSUE THREAD

**Issue by Dbulgin** [OpenTalker/video-retalking#103]
After running the following commands in Ubuntu

python3 inference.py   --face examples/face/1.mp4   --audio examples/audio/1.wav   --outfile results/1_1.mp4

it runs smoothly, until the following.

No CUDA runtime is found, using CUDA_HOME='/usr'
/root/miniconda3/lib/python3.11/site-packages/torchvision/transforms/functional_tensor.py:5: UserWarning: The torchvision.transforms.functional_tensor module is deprecated in 0.15 and will be **removed in 0.17**. Please don't rely on it. You probably just need to use APIs in torchvision.transforms.functional or in torchvision.transforms.v2.functional.
  warnings.warn(

[Info] Using cpu for inference.
[Step 0] Number of frames available for inference: 135
[Step 1] Landmarks Extraction in Video.
Traceback (most recent call last):
  File "/root/video-retalking/inference.py", line 345, in <module>
    main()
  File "/root/video-retalking/inference.py", line 81, in main
    kp_extractor = KeypointExtractor()
                   ^^^^^^^^^^^^^^^^^^^
  File "/root/video-retalking/third_part/face3d/extract_kp_videos.py", line 16, in __init__
    self.detector = face_alignment.FaceAlignment(face_alignment.LandmarksType._2D)
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.11/enum.py", line 783, in __getattr__
    raise AttributeError(name) from None
AttributeError: _2D

**Comment by ziyantengrao** [comment]
the same issue

**Comment by tom20180101** [comment]
face_alignment.LandmarksType._2D --->  face_alignment.LandmarksType.TWO_D

**Comment by hongyao945** [comment]
> try face_alignment.LandmarksType._2D ---> face_alignment.LandmarksType.TWO_D

cooooool

**Comment by f3n-9** [comment]
thx, the problem is solved.

**Comment by usman61** [comment]
it works

**Comment by usman61** [comment]
> try face_alignment.LandmarksType._2D ---> face_alignment.LandmarksType.TWO_D

it works.
