### ISSUE TITLE
face3d module missing

### ISSUE THREAD

**Issue by zachysaur** [OpenTalker/video-retalking#112]
Traceback (most recent call last):
  File "inference.py", line 16, in <module>
    from third_part.face3d.util.preprocess import align_img
  File "C:\Users\xXxXx\Downloads\video-retalking-main\third_part\face3d\util\__init__.py", line 2, in <module>
    from face3d.util import *
ModuleNotFoundError: No module named 'face3d'

**Comment by denzabob** [comment]
The `ModuleNotFoundError` error indicates that your Python script cannot find the `face3d` module. To resolve this issue, you can take the following steps:

1. **Install Required Dependencies**: Make sure you have installed all the necessary dependencies for your project. In your case, `face3d` is presumably an external library that needs to be installed. You can install the `face3d` library using `pip` if it's available:

   ```
   pip install face3d
   ```

   Ensure that you execute this within the same virtual environment (or where you have other dependencies installed) for your project.

2. **Check the Module Path**: Ensure that the path to the `face3d` module is correctly specified in your script. Your error suggests that Python cannot find the `face3d` module in the `third_part.face3d` folder. Double-check that the module path is correct and that the `__init__.py` files are in the right places.

3. **Verify Python Version**: Confirm that you are using the correct version of Python that is compatible with the `face3d` library.

4. **Check the Current Directory**: Make sure your script is being run from the correct directory. Sometimes issues can arise due to the wrong working directory.

5. **Check for Other Conflicts and Module Names**: Ensure there are no module name conflicts with other libraries or files in your project.

If the error persists after following these steps, clarify from where you are attempting to import the `face3d` module and verify its presence in the specified location.

Feel free to provide additional details or error messages if you need further assistance.

**Comment by zachysaur** [comment]
which version of python? 3.8? which mentioned in main page

**Comment by zachysaur** [comment]
![2023-09-23_06h46_48](https://github.com/OpenTalker/video-retalking/assets/124980322/fd405a3e-9cdb-4cbd-bfe7-faf4a95f569e)
i used python 3.10 just like you said

**Comment by jake-nz** [comment]
This problem is not caused by forgetting `pip install face3d` or python versions.
See my comment on the duplicate issue: https://github.com/OpenTalker/video-retalking/issues/78#issuecomment-1851200324

**Comment by supermurkote** [comment]
> ![2023-09-23_06h46_48](https://private-user-images.githubusercontent.com/124980322/270080517-fd405a3e-9cdb-4cbd-bfe7-faf4a95f569e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzMDQ1MTcsIm5iZiI6MTcwNDMwNDIxNywicGF0aCI6Ii8xMjQ5ODAzMjIvMjcwMDgwNTE3LWZkNDA1YTNlLTljZGItNGNiZC1iZmU3LWZhZjRhOTVmNTY5ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwM1QxNzUwMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZmI4M2QwYmYyYWNlMDEzOTQ0MDZiOWU0MTQ0MjA1NDM5ZjlmMzFmYmM2ZjViZDMzYThkZTAwZmJiMzY2NWZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.IBUy6yjcWRXkJNGdsQAqE6FrCVjAaicyAKc7qd3zgCk) i used python 3.10 just like you said

install this ---> conda install pytorch==2.0.1 torchvision==0.15.2 torchaudio==2.0.2 pytorch-cuda=11.8 -c pytorch -c nvidia
