### ISSUE TITLE
doesn't work on windows ?

### ISSUE THREAD

**Issue by nofacedeepfake** [OpenTalker/video-retalking#117]
doesn't work on windows ? D:\lipsing/video-retalking>conda activate video_retalking.

(video_retalking) D:\lipsing/video-retalking>python3 inference.py \
Python
(video_retalking) D:\lipsing\video-retalking> --face examples/face/1.mp4 \.
"--face" is not an internal or external
command, executable program, or batch file.

(video_retalking) D:\lipsing\video-retalking> --audio examples/audio/1.wav \.
"--audio" is not an internal or external
command, executable program, or batch file.

(video_retalking) D:\lipsing\video-retalking> --outfile results/1_1.mp4

**Comment by natlamir** [comment]
might need to remove the newlines and run the command as one line and change python3 to python. i created a fork of this repo with instructions for windows if you wanna check that out

**Comment by linhcentrio** [comment]
> i got this err: "[Info] Using cuda for inference. [Step 0] Number of frames available for inference: 135 [Step 1] Landmarks Extraction in Video. landmark Det:: 100%|█████████████████████████████████████████████████████████████████| 135/135 [00:32<00:00, 4.15it/s] Traceback (most recent call last): File "inference.py", line 345, in main() File "inference.py", line 82, in main lm = kp_extractor.extract_keypoint(frames_pil, './temp/'+base_name+'_landmarks.txt') File "C:\Users\Admin\Downloads\01.Video-Head-Talking\video-retalking\third_part\face3d\extract_kp_videos.py", line 34, in extract_keypoint np.savetxt(os.path.splitext(name)[0]+'.txt', keypoints.reshape(-1)) File "<**array_function** internals>", line 200, in savetxt File "C:\Users\Admin\Downloads\01.Video-Head-Talking\video-retalking\venv\lib\site-packages\numpy\lib\npyio.py", line 1533, in savetxt open(fname, 'wt').close() FileNotFoundError: [Errno 2] No such file or directory: './temp/.\examples\face\1.mp4_landmarks.txt'"

how can i fix it to run on windows?

**Comment by natlamir** [comment]
I used conda with these instructions: https://github.com/natlamir/video-retalking#environment
there is a video too but I don't think I have that linked on the github yet.

**Comment by linhcentrio** [comment]
> I used conda with these instructions: https://github.com/natlamir/video-retalking#environment there is a video too but I don't think I have that linked on the github yet.

Thank natlamir, i've tried your repo and it worked with me.
