### ISSUE TITLE
Trouble getting running on RTX 4090

### ISSUE THREAD

**Issue by KeystoneScience** [OpenTalker/video-retalking#127]
Hello, I would love some help if someone is willing.

I am running this on Ubuntu

my install process is:
```
conda create -n video_retalking python=3.8
conda activate video_retalking

conda install ffmpeg

pip install torch==2.0.0+cu118 torchvision==0.15.1+cu118 torchaudio==2.0.1 --index-url https://download.pytorch.org/whl/cu118

pip install -r requirements.txt
```

I know I need to use this version due to RTX 4090 needing Cuda 11.8.

when I run inference.py, I get:

```
Traceback (most recent call last):
  File "/home/ditto/anaconda3/envs/video_retalking4/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1893, in _run_ninja_build
    subprocess.run(
  File "/home/ditto/anaconda3/envs/video_retalking4/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "inference.py", line 16, in <module>
    from third_part.GPEN.gpen_face_enhancer import FaceEnhancement
  File "/home/ditto/Documents/Ditto/LipSync/video-retalking/third_part/GPEN/gpen_face_enhancer.py", line 8, in <module>
    from face_model.face_gan import FaceGAN
  File "/home/ditto/Documents/Ditto/LipSync/video-retalking/third_part/GPEN/face_model/face_gan.py", line 13, in <module>
    from face_model.gpen_model import FullGenerator
  File "/home/ditto/Documents/Ditto/LipSync/video-retalking/third_part/GPEN/face_model/gpen_model.py", line 16, in <module>
    from face_model.op import FusedLeakyReLU, fused_leaky_relu, upfirdn2d
  File "/home/ditto/Documents/Ditto/LipSync/video-retalking/third_part/GPEN/face_model/op/__init__.py", line 1, in <module>
    from .fused_act import FusedLeakyReLU, fused_leaky_relu
  File "/home/ditto/Documents/Ditto/LipSync/video-retalking/third_part/GPEN/face_model/op/fused_act.py", line 13, in <module>
    fused = load(
  File "/home/ditto/anaconda3/envs/video_retalking4/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1284, in load
    return _jit_compile(
  File "/home/ditto/anaconda3/envs/video_retalking4/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1509, in _jit_compile
    _write_ninja_file_and_build_library(
  File "/home/ditto/anaconda3/envs/video_retalking4/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1624, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "/home/ditto/anaconda3/envs/video_retalking4/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1909, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension 'fused': [1/2] /usr/bin/nvcc  -DTORCH_EXTENSION_NAME=fused -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/ditto/anaconda3/envs/video_retalking4/lib/python3.8/site-packages/torch/include -isystem /home/ditto/anaconda3/envs/video_retalking4/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /home/ditto/anaconda3/envs/video_retalking4/lib/python3.8/site-packages/torch/include/TH -isystem /home/ditto/anaconda3/envs/video_retalking4/lib/python3.8/site-packages/torch/include/THC -isystem /home/ditto/anaconda3/envs/video_retalking4/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_89,code=compute_89 -gencode=arch=compute_89,code=sm_89 --compiler-options '-fPIC' -std=c++17 -c /home/ditto/Documents/Ditto/LipSync/video-retalking/third_part/GPEN/face_model/op/fused_bias_act_kernel.cu -o fused_bias_act_kernel.cuda.o 
FAILED: fused_bias_act_kernel.cuda.o 
/usr/bin/nvcc  -DTORCH_EXTENSION_NAME=fused -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/ditto/anaconda3/envs/video_retalking4/lib/python3.8/site-packages/torch/include -isystem /home/ditto/anaconda3/envs/video_retalking4/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /home/ditto/anaconda3/envs/video_retalking4/lib/python3.8/site-packages/torch/include/TH -isystem /home/ditto/anaconda3/envs/video_retalking4/lib/python3.8/site-packages/torch/include/THC -isystem /home/ditto/anaconda3/envs/video_retalking4/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_89,code=compute_89 -gencode=arch=compute_89,code=sm_89 --compiler-options '-fPIC' -std=c++17 -c /home/ditto/Documents/Ditto/LipSync/video-retalking/third_part/GPEN/face_model/op/fused_bias_act_kernel.cu -o fused_bias_act_kernel.cuda.o 
nvcc fatal   : Unsupported gpu architecture 'compute_89'
ninja: build stopped: subcommand failed.
```

I have been searching for hours now and am pretty stuck. I know other users have used 4090 on this, and I would love any help that could be given. Thank you!

**Comment by KeystoneScience** [comment]
Turns out my core system had Cuda version 11.5 rather than 11.8 – I have updated via https://developer.nvidia.com/cuda-11-8-0-download-archive and am on to other issues
