### ISSUE TITLE
CUDA 11.8 & CUDNN 8 ISSUE | ImportError: DLL load failed while importing _dlib_pybind11: The specified module could not be found.

### ISSUE THREAD

**Issue by EKI-INDRADI** [OpenTalker/video-retalking#133]
```sh
conda activate video_retalking

(video_retalking) V:\_video_retalking\video-retalking>python inference.py --face "examples/face/1.mp4" --audio "examples/audio/1.wav" --outfile "results/1_1.mp4"
V:\_video_retalking\video-retalking\third_part/GPEN\align_faces.py:251: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if align_type is 'cv2_affine':
V:\_video_retalking\video-retalking\third_part/GPEN\align_faces.py:254: SyntaxWarning: "is" with a literal. Did you mean "=="?
  elif align_type is 'cv2_rigid':
V:\_video_retalking\video-retalking\third_part/GPEN\align_faces.py:257: SyntaxWarning: "is" with a literal. Did you mean "=="?
  elif align_type is 'affine':
Traceback (most recent call last):
  File "V:\_video_retalking\video-retalking\inference.py", line 22, in <module>
    from utils.ffhq_preprocess import Croper
  File "V:\_video_retalking\video-retalking\utils\ffhq_preprocess.py", line 31, in <module>
    import dlib
  File "D:\__________________INSTALL\ANACONDA\envs\video_retalking\lib\site-packages\dlib\__init__.py", line 19, in <module>
    from _dlib_pybind11 import *
ImportError: DLL load failed while importing _dlib_pybind11: The specified module could not be found.
```

**Comment by EKI-INDRADI** [comment]
(video_retalking) V:\_video_retalking\video-retalking>python
Python 3.8.18 (default, Sep 11 2023, 13:39:12) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import dlib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\__________________INSTALL\ANACONDA\envs\video_retalking\lib\site-packages\dlib\__init__.py", line 19, in <module>
    from _dlib_pybind11 import *
ImportError: DLL load failed while importing _dlib_pybind11: The specified module could not be found.
>>>

**Comment by EKI-INDRADI** [comment]
dlib_init.py

# Copyright (C) 2020  Davis E. King (davis@dlib.net)
# License: Boost Software License   See LICENSE.txt for the full license.

def add_lib_to_dll_path(path):
    """ On windows you must call os.add_dll_directory() to allow linking to external DLLs.  See
    https://docs.python.org/3.8/whatsnew/3.8.html#bpo-36085-whatsnew.  This function adds the folder
    containing path to the dll search path. 
    """
    try:
        import os
        os.add_dll_directory(os.path.join(os.path.dirname(path), '../../bin'))
    except (AttributeError,KeyError,FileNotFoundError):
        pass

if 'OFF' == 'ON':
    add_lib_to_dll_path('C:/CUDA_11_CUDDN_8/lib/x64/cudnn.lib')
    add_lib_to_dll_path('C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.8/lib/x64/cudart.lib')

from _dlib_pybind11 import *
from _dlib_pybind11 import __version__, __time_compiled__

**Comment by EKI-INDRADI** [comment]
(video_retalking) V:\_video_retalking\video-retalking>python
Python 3.9.18 (main, Sep 11 2023, 14:09:26) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import dlib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\__________________INSTALL\ANACONDA\envs\video_retalking\lib\site-packages\dlib\__init__.py", line 19, in <module>
    from _dlib_pybind11 import *
ImportError: DLL load failed while importing _dlib_pybind11: The specified module could not be found.
>>> dlib.DLIB_USE_CUDA
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'dlib' is not defined
>>> quit()

**Comment by EKI-INDRADI** [comment]
solved : https://github.com/EKI-INDRADI/video-retalking-tested-20231020
