### ISSUE TITLE
checkpoints can not open and RuntimeError: unexpected EOF, expected 73963 more bytes. The file might be corrupted error running on autodl

### ISSUE THREAD

**Issue by shlay158** [OpenTalker/video-retalking#137]
hello,
i got 2 errors to running this project with autodl.
1. checkpoints can not be opened or renamed 
2. got RuntimeError: unexpected EOF, expected 73963 more bytes. The file might be corrupted error running on autodl when running "python inference.py --face examples/face/1.mp4 --audio examples/audio/1.wav --outfile results/1_1.mp4"
anybody can do help?

**Comment by xin-duan** [comment]
@shlay158, 
    I hit similar error which is caused by incomplete or failure of downloading some necessarcy checkpoints models, check your log and manually download required models and rerun
for example, my error is like below which means you need to check if s3fd-619a316812.pth has been downloaded successfully, you can see s3fd-619a316812.pth has not been downloaded completely so folollowing check failed:
Output------------------------------------------------------------------------
[Step 1] Landmarks Extraction in Video.
Downloading: "https://www.adrianbulat.com/downloads/python-fan/s3fd-619a316812.pth" to C:\Users\dx/.cache\torch\hub\checkpoints\s3fd-619a316812.pth
 32%|████████████████████████▍                                                    | 27.2M/85.7M [00:03<00:08, 7.43MB/s]
Traceback (most recent call last):
  File "C:\AI\video-retalking\inference.py", line 345, in <module>
    main()
  File "C:\AI\video-retalking\inference.py", line 81, in main
    kp_extractor = KeypointExtractor()
  File "C:\AI\video-retalking\third_part\face3d\extract_kp_videos.py", line 16, in __init__
    self.detector = face_alignment.FaceAlignment(face_alignment.LandmarksType.TWO_D)  # duanxin change _2D to TWO_D
  File "C:\AI\system\miniconda3\lib\site-packages\face_alignment\api.py", line 80, in __init__
    self.face_detector = face_detector_module.FaceDetector(device=device, verbose=verbose, **face_detector_kwargs)
  File "C:\AI\system\miniconda3\lib\site-packages\face_alignment\detection\sfd\sfd_detector.py", line 24, in __init__
    model_weights = load_url(models_urls['s3fd'])
  File "C:\AI\system\miniconda3\lib\site-packages\torch\hub.py", line 750, in load_state_dict_from_url
    return torch.load(cached_file, map_location=map_location)
  File "C:\AI\system\miniconda3\lib\site-packages\torch\serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "C:\AI\system\miniconda3\lib\site-packages\torch\serialization.py", line 1051, in _legacy_load
    typed_storage._untyped_storage._set_from_file(
RuntimeError: unexpected EOF, expected 2659590 more bytes. The file might be corrupted.

Hope this help you.
