### ISSUE TITLE
When there is no face in some frames in video, how to handle that situation.

### ISSUE THREAD

**Issue by Someonetoldme584** [OpenTalker/video-retalking#150]
Traceback (most recent call last):
  File "inference.py", line 345, in <module>
    main()
  File "inference.py", line 214, in main
    for i, (img_batch, mel_batch, frames, coords, img_original, f_frames) in enumerate(tqdm(gen, desc='[Step 6] Lip Synthesis:', total=int(np.ceil(float(len(mel_chunks)) / args.LNet_batch_size)))):
  File "C:\Users\as-aj\miniconda3\envs\video_retalking\lib\site-packages\tqdm\std.py", line 1182, in __iter__
    for obj in iterable:
  File "inference.py", line 295, in datagen
    face_det_results = face_detect(full_frames, args, jaw_correction=True)
  File "C:\AI\opentalker\video-retalking\utils\inference_utils.py", line 133, in face_detect
    raise ValueError('Face not detected! Ensure the video contains a face in all the frames.')
ValueError: Face not detected! Ensure the video contains a face in all the frames.

I want to skip the face even if there is no face how to do it?

**Comment by kalpesh-maru** [comment]
Did you find the solution?
