### ISSUE TITLE
 setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (5,) + inhomogeneous part.

### ISSUE THREAD

**Issue by zhixingrenai** [OpenTalker/video-retalking#35]
[Step 2] 3DMM Extraction In Video::   0%|                                                                                                                                                                      | 0/135 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "inference.py", line 342, in <module>
    main()
  File "inference.py", line 100, in main
    trans_params, im_idx, lm_idx, _ = align_img(frame, lm_idx, lm3d_std)
  File "G:\pythonProject\third_part\face3d\util\preprocess.py", line 196, in align_img
    trans_params = np.array([w0, h0, s, t[0], t[1]])
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (5,) + inhomogeneous part.
PS G:\pythonProject>

**Comment by zhixingrenai** [comment]
step 2 error, who know it, thank you

**Comment by kunncheng** [comment]
There is a similar [issue](https://github.com/OpenTalker/video-retalking/issues/34).
What is your `numpy` version

**Comment by deepakkupanda** [comment]
Replace the line     trans_params = np.array([w0, h0, s, np.asscalar(t[0]), np.asscalar(t[1])])
with below lines
    trans_params = np.array([w0, h0, s])
    trans_params = np.append(trans_params, t[0])
    trans_params = np.append(trans_params, t[1])
It worked for me.

**Comment by zhixingrenai** [comment]
is ok now, numpy version change is ok

**Comment by LeoLovechest** [comment]
> 

as I am having the same error what fixed it was it the numpy version change? what version did you end up using?

**Comment by jasonpraful** [comment]
downgrading to `numpy==1.23.1` fixed it without having to replace any text as stated above

**Comment by Thharshita** [comment]
craft error

**Comment by zouzhekang** [comment]
> numpy==1.23.1

no.you broken my env.....
I think the true way is 
pip uninstall numba numpy
pip install numpy==1.23.4 numba
