### ISSUE TITLE
FileNotFoundError: [WinError 2]

### ISSUE THREAD

**Issue by waveboy800** [OpenTalker/video-retalking#37]
where I came in the sixth step,it broke out.  
Traceback (most recent call last):
  File "inference.py", line 342, in <module>
    main()
  File "inference.py", line 271, in main
    subprocess.call(command, shell=platform.system() != 'Windows')
  File "E:\anaconda\envs\video_retalking\lib\subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "E:\anaconda\envs\video_retalking\lib\subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "E:\anaconda\envs\video_retalking\lib\subprocess.py", line 1311, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

**Comment by kunncheng** [comment]
Have you installed `ffmpeg`?
You can follow [here](https://github.com/OpenTalker/SadTalker/issues/243#issuecomment-1522171935) to install it on Windows.
