### ISSUE TITLE
RuntimeError: storage has wrong size: expected 0 got 256

### ISSUE THREAD

**Issue by w4l6** [OpenTalker/video-retalking#42]
After deploying according to the document, the following error is reported:

RuntimeError: storage has wrong size: expected 0 got 256

Please ask the Great God for help. thx！

**Comment by kunncheng** [comment]
Please provide complete error information.

Which line of code caused the error?

**Comment by w4l6** [comment]
多谢。错误信息如下

File "inference.py"Tine 342. in <module>main0File "inference.py", Tine 33, in mainsize=512，mode1="GPEN-BFR-512',enhancer = FaceEnhancement(base dir='checkpoints'use sr=False.File "/root/autodl-tmp/video-retalking/third_part/GPEN/gpen_face_enhancer.py”,Tine 18. in initself.facedetector = RetinaFaceDetection(base dirdewice)File/root/autodI-tmp/video-retalking/third part/GPEN/face detect/retinaface detection.py", Tine 27, in initself.load mode1()File "/root/autodl-tmp/video-retalking/third part/GPEN/face detect/retinaface detection.py", Tine 51, in load modeFi'eetrrone monsconda3/envsaatsrkinorefpainenonatk stap-pocatdon torch, deviee cpuon pv", line 608. in loadreturnlegacy load(openedocation.pickle module.**pickle load args)m30File "/root/miniconda3/envs/retalking/lib/python3.8/site-packages/torch/serialization.py", line 794, in _legacy_loadeserialized obiects[key7.set from file(foffset.f should read directly)untimeError: storage has wrona size:expected 0 got 256

**Comment by w4l6** [comment]
[Info] Using cuda for inference.
Traceback (most recent call last):
  File "inference.py", line 342, in <module>
    main()
  File "inference.py", line 33, in main
    enhancer = FaceEnhancement(base_dir='checkpoints', size=512, model='GPEN-BFR-512', use_sr=False, \
  File "/root/autodl-tmp/video-retalking/third_part/GPEN/gpen_face_enhancer.py", line 18, in __init__
    self.facedetector = RetinaFaceDetection(base_dir, device)
  File "/root/autodl-tmp/video-retalking/third_part/GPEN/face_detect/retinaface_detection.py", line 27, in __init__
    self.load_model()
  File "/root/autodl-tmp/video-retalking/third_part/GPEN/face_detect/retinaface_detection.py", line 51, in load_model
    pretrained_dict = torch.load(self.pretrained_path, map_location=torch.device('cpu'))
  File "/root/miniconda3/envs/retalking/lib/python3.8/site-packages/torch/serialization.py", line 608, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/root/miniconda3/envs/retalking/lib/python3.8/site-packages/torch/serialization.py", line 794, in _legacy_load
    deserialized_objects[key]._set_from_file(f, offset, f_should_read_directly)
RuntimeError: storage has wrong size: expected 0 got 256

**Comment by kunncheng** [comment]
可能是retinaface预训练模型下载过程中出现问题，可以试试重新下载一下

**Comment by w4l6** [comment]
多谢多谢
