### ISSUE TITLE
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (5,) + inhomogeneous part.

### ISSUE THREAD

**Issue by ltbjwzttzz** [OpenTalker/video-retalking#43]
大神您好，请帮忙看看这个错误怎么解决。搞了8个小时，目前卡在这个错误，实在搞不定了，辛苦您帮忙看下，多谢多谢。
我的环境是本地电脑win10，64位，显卡GTX960 4G显存，已经安装了anaconda3，以及python3.8，cuda11.1，在环境变量里也配置了。
在powershell中输入命令：
python inference.py --face examples/face/1.mp4 --audio examples/audio/1.wav --outfile results/1_1.mp4

输出结果：
C:\Python\Python38\lib\site-packages\setuptools\distutils_patch.py:25: UserWarning: Distutils was imported before Setuptools. This usage is discouraged and may exhibit undesirable behaviors or errors. Please use Setuptools' objects directly or at least import Setuptools first.
  warnings.warn(
[Info] Using cuda for inference.
[Step 0] Number of frames available for inference: 135
[Step 1] Landmarks Extraction in Video.
landmark Det:: 100%|█████████████████████████████████████████████████████████████████| 135/135 [00:25<00:00,  5.29it/s]
[Step 2] 3DMM Extraction In Video::   0%|                                                      | 0/135 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "inference.py", line 342, in <module>
    main()
  File "inference.py", line 100, in main
    trans_params, im_idx, lm_idx, _ = align_img(frame, lm_idx, lm3d_std)
  File "C:\ai\video-retalking\third_part\face3d\util\preprocess.py", line 196, in align_img
    trans_params = np.array([w0, h0, s, t[0], t[1]])
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (5,) + inhomogeneous part.

**Comment by kunncheng** [comment]
可以参考下这个[issue]( https://github.com/OpenTalker/video-retalking/issues/35)，似乎是一样的问题

**Comment by ltbjwzttzz** [comment]
多谢多谢，我也刚刚看到，正在降级numpy==1.23.1

**Comment by ltbjwzttzz** [comment]
我刚刚看到，试试降级numpy==1.2.1的方法，感谢您的回复

**Comment by ltbjwzttzz** [comment]
conda install numpy==1.23.1
降级到1.23.1可以正常运行了，谢谢。

**Comment by kunncheng** [comment]
Have fun~😊
