### ISSUE TITLE
原来顺利运行的，突然报错step1

### ISSUE THREAD

**Issue by qiu8888** [OpenTalker/video-retalking#50]
[Step 1] Landmarks Extraction in Video.
Traceback (most recent call last):
  File "inference.py", line 342, in <module>
    main()
  File "inference.py", line 78, in main
    kp_extractor = KeypointExtractor()
  File "C:\Users\Qiyun\video-retalking\third_part\face3d\extract_kp_videos.py", line 16, in __init__
    self.detector = face_alignment.FaceAlignment(face_alignment.LandmarksType._2D)
  File "C:\Users\Qiyun\miniconda3\envs\video_retalking\lib\enum.py", line 384, in __getattr__
    raise AttributeError(name) from None
AttributeError: _2D

**Comment by crankyz** [comment]
Same issue, that something wrong with new version of some package, bc initial one worked fine.
