### ISSUE TITLE
Needhelp! Error in step2

### ISSUE THREAD

**Issue by nagaki09** [OpenTalker/video-retalking#56]
[Step 0] Number of frames available for inference: 135
[Step 1] Landmarks Extraction in Video.
landmark Det:: 100%|██████████| 135/135 [00:24<00:00,  5.48it/s]
[Step 2] 3DMM Extraction In Video::   0%|          | 0/135 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "C:\Users\Administrator\video-retalking\inference.py", line 342, in <module>
    main()
  File "C:\Users\Administrator\video-retalking\inference.py", line 100, in main
    trans_params, im_idx, lm_idx, _ = align_img(frame, lm_idx, lm3d_std)
  File "C:\Users\Administrator\video-retalking\third_part\face3d\util\preprocess.py", line 196, in align_img
    trans_params = np.array([w0, h0, s, t[0], t[1]])
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (5,) + inhomogeneous part.
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\envs\video_retalking\lib\site-packages\gradio\routes.py", line 437, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\ProgramData\anaconda3\envs\video_retalking\lib\site-packages\gradio\blocks.py", line 1352, in process_api
    result = await self.call_function(
  File "C:\ProgramData\anaconda3\envs\video_retalking\lib\site-packages\gradio\blocks.py", line 1077, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\ProgramData\anaconda3\envs\video_retalking\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\ProgramData\anaconda3\envs\video_retalking\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\ProgramData\anaconda3\envs\video_retalking\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Users\Administrator\video-retalking\webUI.py", line 29, in convert
    processed_output = process_segment(video_seg, audio_seg, i)
  File "C:\Users\Administrator\video-retalking\webUI.py", line 80, in process_segment
    subprocess.run(command, check=True)
  File "C:\ProgramData\anaconda3\envs\video_retalking\lib\subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['python', 'inference.py', '--face', 'temp/video\\1.mp4', '--audio', 'temp/audio\\1-0-100.wav', '--outfile', 'results/62011_0.mp4']' returned non-zero exit status 1.

**Comment by kunncheng** [comment]
You can try this:  https://github.com/OpenTalker/video-retalking/issues/35#issuecomment-1542944601
