### ISSUE TITLE
[Step 6]报错

### ISSUE THREAD

**Issue by superdreams** [OpenTalker/video-retalking#57]
[Step 6] Lip Synthesis::   0%|                                                                                   | 0/8 [00:26<?, ?it/s]
Traceback (most recent call last):
  File "inference.py", line 342, in <module>
    main()
  File "inference.py", line 218, in main
    pred, low_res = model(mel_batch, img_batch, reference)
  File "/home/ubuntu/anaconda3/envs/videotalking/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/video-retalking/models/ENet.py", line 123, in forward
    out = conv1(out, style_code)  # 96, 192, 384
  File "/home/ubuntu/anaconda3/envs/videotalking/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/video-retalking/models/base_blocks.py", line 526, in forward
    out = self.modulated_conv(x, style) * 2**0.5  # for conversion
  File "/home/ubuntu/anaconda3/envs/videotalking/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/video-retalking/models/base_blocks.py", line 500, in forward
    x = F.interpolate(x, scale_factor=2, mode='bilinear', align_corners=False)
  File "/home/ubuntu/anaconda3/envs/videotalking/lib/python3.8/site-packages/torch/nn/functional.py", line 3709, in interpolate
    return torch._C._nn.upsample_bilinear2d(input, output_size, align_corners, scale_factors)
RuntimeError: CUDA out of memory. Tried to allocate 2.44 GiB (GPU 0; 10.76 GiB total capacity; 2.83 GiB already allocated; 1.74 GiB free; 6.55 GiB reserved in total by PyTorch)

**Comment by TalhaaaYaqoob** [comment]
have you solve that error ?

**Comment by HzChenCe163** [comment]
+1
