### ISSUE TITLE
Error using webUI

### ISSUE THREAD

**Issue by G-force78** [OpenTalker/video-retalking#58]
Traceback (most recent call last):
  File "/content/video-retalking/inference.py", line 342, in <module>
    main()
  File "/content/video-retalking/inference.py", line 33, in main
    enhancer = FaceEnhancement(base_dir='checkpoints', size=512, model='GPEN-BFR-512', use_sr=False, \
  File "/content/video-retalking/third_part/GPEN/gpen_face_enhancer.py", line 18, in __init__
    self.facedetector = RetinaFaceDetection(base_dir, device)
  File "/content/video-retalking/third_part/GPEN/face_detect/retinaface_detection.py", line 27, in __init__
    self.load_model()
  File "/content/video-retalking/third_part/GPEN/face_detect/retinaface_detection.py", line 51, in load_model
    pretrained_dict = torch.load(self.pretrained_path, map_location=torch.device('cpu'))
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'checkpoints/RetinaFace-R50.pth'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/routes.py", line 437, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1352, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1077, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/content/video-retalking/webUI.py", line 29, in convert
    processed_output = process_segment(video_seg, audio_seg, i)
  File "/content/video-retalking/webUI.py", line 80, in process_segment
    subprocess.run(command, check=True)
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['python', 'inference.py', '--face', 'temp/audio/131_000.mp4', '--audio', 'temp/video/498_000.mp3', '--outfile', 'results/26538_0.mp4']' returned non-zero exit status 1.

**Comment by G-force78** [comment]
Ok looks like Im missing a load of checkpoints..
