### ISSUE TITLE
运行出错

### ISSUE THREAD

**Issue by kajfblsdkgnlsndg** [OpenTalker/video-retalking#71]
landmark Det:: 100%|█████████████████████████████████████████████████████████████████| 493/493 [00:34<00:00, 14.38it/s]
Traceback (most recent call last):
  File "inference.py", line 345, in <module>
    main()
  File "inference.py", line 82, in main
    lm = kp_extractor.extract_keypoint(frames_pil, './temp/'+base_name+'_landmarks.txt')
  File "D:\AIgongju\video-retalking\third_part\face3d\extract_kp_videos.py", line 34, in extract_keypoint
    np.savetxt(os.path.splitext(name)[0]+'.txt', keypoints.reshape(-1))
  File "<__array_function__ internals>", line 180, in savetxt
  File "D:\Anaconda3\envs\video_retalking\lib\site-packages\numpy\lib\npyio.py", line 1523, in savetxt
    open(fname, 'wt').close()
OSError: [Errno 22] Invalid argument: './temp/C:\\Users\\HKwang\\Desktop\\777.mp4_landmarks.txt'  这个错误是什么原因

**Comment by ruanzhuinfo** [comment]
me too

**Comment by pythonzm** [comment]
Windows下路径分隔符改成 / ，不要用默认的 \

**Comment by johndpope** [comment]
https://chat.openai.com/share/568ee28a-99c6-4ff5-8ab4-9bb9eda77fa8
