### ISSUE TITLE
step2时运行出错 麻烦能帮忙看一下吗

### ISSUE THREAD

**Issue by wolixixi** [OpenTalker/video-retalking#72]
[Step 2] 3DMM Extraction In Video::   0%|                                                      | 0/155 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "D:\Vretalking\inference.py", line 345, in <module>
    main()
  File "D:\Vretalking\inference.py", line 103, in main
    trans_params, im_idx, lm_idx, _ = align_img(frame, lm_idx, lm3d_std)
  File "D:\Vretalking\third_part\face3d\util\preprocess.py", line 196, in align_img
    trans_params = np.array([w0, h0, s, t[0], t[1]])
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (5,) + inhomogeneous part.
Traceback (most recent call last):
  File "C:\Users\27775\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\routes.py", line 437, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\27775\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\blocks.py", line 1352, in process_api
    result = await self.call_function(
  File "C:\Users\27775\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\blocks.py", line 1077, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\27775\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\27775\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Users\27775\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "D:\Vretalking\webui.py", line 29, in convert
    processed_output = process_segment(video_seg, audio_seg, i)
  File "D:\Vretalking\webui.py", line 80, in process_segment
    subprocess.run(command, check=True)
  File "C:\Users\27775\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['python', 'inference.py', '--face', 'temp/video\\srcVideo.MP4', '--audio', 'temp/audio\\drvWav-0-100.wav', '--outfile', 'results/73572_0.mp4']' returned non-zero exit status 1.

**Comment by kunncheng** [comment]
Please refer to https://github.com/OpenTalker/video-retalking/issues/35#issuecomment-1542944601

**Comment by wolixixi** [comment]
> Please refer to [#35 (comment)](https://github.com/OpenTalker/video-retalking/issues/35#issuecomment-1542944601)

wow fixed thanks so much
