### ISSUE TITLE
UnboundLocalError: local variable 'mask_sharp' referenced before assignment

### ISSUE THREAD

**Issue by SuperMaximus1984** [OpenTalker/video-retalking#81]
Does anybody know why this happens?
```
[Step 5] Reference Enhancement:  67%|██████████████████████████████████▊                 | 545/813 [02:34<01:15,  3.53it/s]
Traceback (most recent call last):
  File "inference.py", line 345, in <module>
    main()
  File "inference.py", line 201, in main
    pred, _, _ = enhancer.process(img, img, face_enhance=True, possion_blending=False)
  File "d:\Python Stuff\video-retalking\third_part\GPEN\gpen_face_enhancer.py", line 113, in process
    mask_sharp = cv2.GaussianBlur(mask_sharp, (0,0), sigmaX=1, sigmaY=1, borderType = cv2.BORDER_DEFAULT)
UnboundLocalError: local variable 'mask_sharp' referenced before assignment
```

**Comment by komilaria** [comment]
video & audio size should be  the same

**Comment by SuperMaximus1984** [comment]
@komilaria 
What do you mean? Timing in seconds?
I used to succeed with different timing of WAV & MP4 though.

**Comment by kunncheng** [comment]
Please refer to https://github.com/OpenTalker/video-retalking/issues/14
