### ISSUE TITLE
BIG HELP, please assist 

### ISSUE THREAD

**Issue by FeShAdoW92** [OpenTalker/video-retalking#92]
C:\Users\alxtu\AppData\Local\Temp\gradio\763cacee5ab1055764617652b7bcefd507cfebcd\1.mp4 C:\Users\alxtu\AppData\Local\Temp\gradio\001bd1cf9d6fcf462c7cd65071ccdda139769242\1-0-100.wav
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\shutil.py", line 816, in move
    os.rename(src, real_dst)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\alxtu\\AppData\\Local\\Temp\\gradio\\763cacee5ab1055764617652b7bcefd507cfebcd\\1.mp4' -> 'temp/video\\1.mp4'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alxtu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\alxtu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "C:\Users\alxtu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\gradio\blocks.py", line 1109, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "c:\retalk\video-retalking-main\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "c:\retalk\video-retalking-main\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "c:\retalk\video-retalking-main\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Users\alxtu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\gradio\utils.py", line 706, in wrapper
    response = f(*args, **kwargs)
  File "c:\retalk\video-retalking-main\webUI.py", line 21, in convert
    shutil.move(video, video_path)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\shutil.py", line 836, in move
    copy_function(src, real_dst)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\shutil.py", line 434, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\shutil.py", line 256, in copyfile
    with open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: 'temp/video\\1.mp4'

I dont know how to fix the problem with temp file. Please explain, as I am noob and beginner in this, thank you!

**Comment by ZXCMiller** [comment]
+1

**Comment by supermurkote** [comment]
Create a "temp" folder if it doesn't exist "*\video-retalking\temp"

If that doesn't help, reinstall "gradio"

pip install gradio
or 
pip reinstall gradio
