### ISSUE TITLE
Help me, please 

### ISSUE THREAD

**Issue by coffeecoke** [OpenTalker/video-retalking#94]
Traceback (most recent call last):
File "inference.py", line 22, in <module>
from utils.ffhq_preprocess import Croper
File "F:\tanghuan\video-retalking\utils\ffhq_preprocess.py", line 31, in <module>
import dlib
File "F:\tanghuan\anaconda3\envs\video_retalking\lib\site-packages\dlib\__init__.py", line 19, in <module>
from _dlib_pybind11 import *
ImportError: DLL load failed while importing _dlib_pybind11

**Comment by MING8276** [comment]
you should change the version of the dlib
