### ISSUE TITLE
windows10、 Python3.8、运行step1报错   raise AttributeError(name) from None AttributeError: _2D

### ISSUE THREAD

**Issue by DevHuang** [OpenTalker/video-retalking#99]
(videoing) E:\video-retalking-main>python inference.py  --face examples/face/1.mp4  --audio examples/audio/1.wav  --outfile results/1_3.mp4

D:\project\envs\videoing\lib\site-packages\torchvision\transforms\functional_tensor.py:5: UserWarning: The torchvision.transforms.functional_tensor module is deprecated in 0.15 and will be **removed in 0.17**. Please don't rely on it. You probably just need to use APIs in torchvision.transforms.functional or in torchvision.transforms.v2.functional.
  warnings.warn(
[Info] Using cpu for inference.
[Step 0] Number of frames available for inference: 135
[Step 1] Landmarks Extraction in Video.
Traceback (most recent call last):
  File "inference.py", line 345, in <module>
    main()
  File "inference.py", line 81, in main
    kp_extractor = KeypointExtractor()
  File "E:\video-retalking-main\third_part\face3d\extract_kp_videos.py", line 16, in __init__
    self.detector = face_alignment.FaceAlignment(face_alignment.LandmarksType._2D)
  File "D:\project\envs\videoing\lib\enum.py", line 384, in __getattr__
    raise AttributeError(name) from None
AttributeError: _2D

**Comment by guoqiqi387** [comment]
You can change the error location to TWO_D

**Comment by f3n-9** [comment]
我有相同的报错信息，请问解决了吗
